track/urls.py
from django.conf.urls import url
from django.urls import include, path
from django.contrib import admin
from tracker import views as tracker_views

urlpatterns = [
    path('tracker/', include('tracker.urls')),
    path('users/', include('users.urls')),
    url(r'^admin/', admin.site.urls),
    url('', include('social_django.urls', namespace='social')),
    url(r'^$', tracker_views.index, name="home"),
]

tracker/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'tracker'

urlpatterns = [
    url(r'^dashboard/$'   , views.tracker_dashboard, name="tracker_dashboard"),
    url(r'^exercise/$'    , views.tracker_exercise, name="tracker_exercise"),
    url(r'^profile/$'     , views.tracker_profile, name="tracker_profile"),
    path('', views.index  , name='index'),
]

users/urls.py
from django.urls import path
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    path('signup/', views.signup, name='signup'),
    path('', views.index, name='index'),
]

tracker/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from social_django.models import UserSocialAuth

class NutritionInfo(models.Model):
    name = models.CharField(max_length=500,null=True, blank=True)
    info = models.CharField(max_length=500,null=True, blank=True)
    glycemicindex = models.IntegerField(null=True, blank=True)
    glycemicload = models.IntegerField(null=True, blank=True)
    def __str__(self):
        return self.name

# Create your models here.
class Entries(models.Model):
    Date                   = models.DateField(auto_now_add=True)
    DateTime               = models.DateTimeField(auto_now_add=True)
    Username               = models.CharField(max_length=200,null=True, blank=True)
    Tracking               = models.CharField(max_length=200,null=True, blank=True)
    String_Value           = models.CharField(max_length=200,null=True, blank=True)
    Numerical_Value        = models.CharField(max_length=200,null=True, blank=True)
    Additional_Information = models.CharField(max_length=200,null=True, blank=True)
    Nurtrition_Info        = models.ForeignKey(NutritionInfo, on_delete=models.CASCADE,null=True, blank=True)
    fbid                   = models.CharField(max_length=200,null=True, blank=True)

    def __str__(self):
            return self.Username

class Exercise(models.Model):
    id = models.CharField(max_length=100, primary_key=True)
    title = models.CharField(max_length=100)
    def __str__(self):
        return self.title

class UserProfile(models.Model):
    #user = models.OneToOneField(User, on_delete=models.CASCADE)
    user  = models.OneToOneField(
                User,
                on_delete=models.CASCADE,
                blank=True,
                null=True,
                unique=True,
                related_name='userprofile'
            )
    age    = models.IntegerField(null=True, blank=True)
    weight = models.IntegerField(null=True, blank=True)
    height = models.IntegerField(null=True, blank=True)
    gender = models.CharField(max_length=200,null=True, blank=True)
    weight_tracker = models.BooleanField(default=True)
    bm_tracker = models.BooleanField(default=False)
    countdown_number = models.IntegerField(null=True, blank=True, default=60)

    def __str__(self):
            return self.user.username

tracker/forms.py
from django import forms
from . import models
from django.forms import ModelForm
from .models import UserProfile

class CreateEntry(forms.ModelForm):
    class Meta:
        model = models.Entries
        fields = ['Tracking','String_Value','Numerical_Value','Additional_Information']
        exclude =[
            'Numerical_Value'
        ]
        widgets = {
            'Tracking': forms.HiddenInput(),
        }
        labels = {
            "String_Value": "Food"
        }



class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        weight_tracker = forms.BooleanField(initial=True)
        fields = ['age','weight','height','countdown_number']

tracker/views/index.py
from .. import forms
from ..models import Entries
from ..models import Exercise
from ..tables import EntriesTable
from datetime import datetime
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render
import logging

logging.basicConfig(level=logging.DEBUG)
today = datetime.now().date()

# Create your views here.
def index(request):
    if request.method == 'POST':
        form = forms.CreateEntry(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.userid = request.user
            instance.save()
            return redirect('tracker:index')
    else:
        form = forms.CreateEntry()

    todays_top_users     = Entries.objects.all()\
                            .filter(Date=today, Tracking="Exercise")\
                            .exclude(Username="Anonymous")\
                            .exclude(Additional_Information="Skipped")\
                            .values('Username','fbid')\
                            .annotate(total=Count('Username'))\
                            .order_by('-total')

    top_users            = Entries.objects.all()\
                            .values('Username','fbid')\
                            .annotate(total=Count('Username'))\
                            .exclude(Username="Anonymous")\
                            .exclude(Additional_Information="Skipped")\
                            .order_by('-total')

    exercise_count       = Exercise.objects.all().count()

    entries_count        = Entries.objects.all()\
                            .filter(Tracking="Exercise")\
                            .exclude(Additional_Information="Skipped")\
                            .count()

    top_exercises        = Entries.objects.all()\
                            .filter(Tracking="Exercise")\
                            .exclude(Additional_Information="Skipped")\
                            .values('String_Value')\
                            .annotate(total=Count('String_Value'))\
                            .order_by('-total')[:10]

    top_exercise_skipped = Entries.objects.all()\
                            .filter(Tracking="Exercise", Additional_Information="Skipped")\
                            .values('String_Value')\
                            .annotate(total=Count('String_Value'))\
                            .order_by('-total')[:10]

    entries              = Entries.objects.all()\
                            .filter(Tracking="Exercise",Date=today)\
                            .exclude(Additional_Information="Skipped")\
                            .order_by('-DateTime')

    entriestable = EntriesTable(entries)

    return render(
        request, 'tracker/tracker_list.html',
        {
            'entries_count':entries_count,
            'entries': entries,
            'entriestable' : entriestable,
            'exercise_count': exercise_count,
            'form': form ,
            'todays_top_users': todays_top_users,
            'top_exercise_skipped': top_exercise_skipped,
            'top_exercises': top_exercises,
            'top_users': top_users
        }
    )

tracker/views/tracker_dashboard.py
from .. import forms
from ..models import Entries
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.db.models.functions import TruncDay
from django.http import HttpResponse
from django.shortcuts import render
import logging
import pandas as pd
from datetime import datetime

logging.basicConfig(level=logging.DEBUG)

@login_required(login_url="/users/login/")
def tracker_dashboard(request):

    ## EXERCISE

    exercise_entry_queryset = Entries.objects.filter(Username=request.user,Tracking="Exercise")\
                                             .exclude(Additional_Information="Skipped")\
                                             .values('Date','String_Value')
    exercise_labels = []
    exercise_data = []
    
    if exercise_entry_queryset:
        df_exercise = pd.DataFrame(list(exercise_entry_queryset))
        today = (pd.Timestamp("today") - pd.DateOffset(days=13)).strftime("%m-%d-%Y")
        idx = pd.Series(pd.date_range(today,periods=14))
        df_exercise.index = df_exercise['Date']
        del df_exercise['Date']

        df_exercise = df_exercise.groupby(df_exercise.index)\
               .count()\

        df_exercise = df_exercise.reindex(idx, fill_value=0)

        exercise_labels = df_exercise.index.tolist()
        exercise_labels = [ exercise_label.strftime("%d %b") for exercise_label in exercise_labels]
        exercise_data = df_exercise["String_Value"].tolist()


    return render(request, 'tracker/tracker_dashboard.html',
                    {
                        'exercise_labels' : exercise_labels,
                        'exercise_data' : exercise_data
                    } )

tracker/views/tracker_exercise.py
from .. import forms
from ..models import Entries
from ..models import Exercise
from ..models import UserProfile
from ..tables import EntriesTable
from datetime import datetime
from django.http import HttpResponse
from django.shortcuts import render
import logging

logging.basicConfig(level=logging.DEBUG)

def tracker_exercise(request):
    if request.method == 'POST':
        #post_exercise_id = request.GET['exercise_id']
        if request.POST.get('skip_exercise_id'):
            skip_exercise_id = request.POST['skip_exercise_id']
            logging.debug('POST - Skip Exercise : {}'.format(skip_exercise_id))
            Entries.objects.filter(id=skip_exercise_id).update(Additional_Information="Skipped")
        if request.POST.get('complete_exercise_id'):
            complete_exercise_id = request.POST['complete_exercise_id']
            logging.debug('POST - Complete Exercise : {}'.format(complete_exercise_id))
            Entries.objects.filter(id=complete_exercise_id).update(Additional_Information="Completed")
    exercise = (Exercise.objects.order_by('?').first())
    username="Anonymous"
    fbid=""
    if request.user.is_authenticated:
        username=request.user
        fb = request.user.social_auth.filter(provider='facebook').values('uid').first()
        if fb:
            fbid = fb.get("uid")
    l = Entries(Username=username,
                Tracking="Exercise",
                String_Value=exercise,
                Numerical_Value="60",
                Additional_Information="Skipped",
                fbid=fbid)
    l.save()
    logging.debug('+++ tracker_exercise view +++')
    form = forms.CreateEntry()
    form.initial["Tracking"] = "Exercise"
    today = datetime.now().date()
    logging.debug('todays_date : {}'.format(today))
    entries = Entries.objects.all()\
                              .filter(Username=username,Tracking="Exercise",Date=today)\
                              .exclude(Additional_Information="Skipped")\
                              .order_by('-DateTime')
    entriestable = EntriesTable(entries)

    countdown_number = 60

    # if request.user.is_authenticated:
    #     profile_user = UserProfile.objects.filter(user=request.user)
    #     countdown_number = profile_user[0].countdown_number


    return render(request, 'tracker/tracker_exercise.html', {
            'form': form ,
            'exercise': exercise,
            "exercise_id": l.id,
            'entries_count': Entries.objects.all()
                                      .filter(Username=username,Tracking="Exercise",Date=today)
                                      .exclude(Additional_Information="Skipped")
                                      .count(),
            'exercises_skipped': Entries.objects.all()
                                      .filter(Username=username,Tracking="Exercise",Additional_Information="Skipped")
                                      .count(),
            'entriestable' : entriestable,

            'countdown_number' : countdown_number
        } )

tracker/views/tracker_profile.py
from .. import forms
from ..forms import UserProfileForm
from ..models import Entries
from ..models import Exercise
from ..models import UserProfile
from datetime import datetime
from django.db.models import Count
from django.db.models.functions import TruncDay
from django.http import HttpResponse
from django.shortcuts import render
import logging
import urllib.request as urllib2
import json

logging.basicConfig(level=logging.DEBUG)
today = datetime.now().date()

def tracker_profile(request):
    form = UserProfileForm()
    username="Anonymous"
    if request.user.is_authenticated:
        user_exists = UserProfile.objects.all().filter(user=request.user)

        username=request.user
        # Change this to .first() instead of referencing array like [0]
        profile_user = UserProfile.objects.filter(user=request.user)
        #print("facebook ID : {}".format(request.user.social_auth.get(provider='facebook').uid))
        social_user = request.user.social_auth.filter(provider='facebook').first()


    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            # this logic is lame need to fix it up
            if user_exists:
                obj = UserProfile.objects.get(user=request.user)
                if form.cleaned_data['age']:
                    obj.age = form.cleaned_data['age']
                if form.cleaned_data['weight']:
                    obj.weight = form.cleaned_data['weight']
                if form.cleaned_data['height']:
                    obj.height = form.cleaned_data['height']
                if form.cleaned_data['countdown_number']:
                    obj.countdown_number = form.cleaned_data['countdown_number']
                obj.save()
            else:
                user_profile = form.save(commit=False)
                user_profile.user = username
                user_profile.age = form.cleaned_data['age']
                user_profile.weight = form.cleaned_data['weight']
                user_profile.height = form.cleaned_data['height']
                user_profile.countdown_number = form.cleaned_data['countdown_number']
                user_profile.save()

    bmi = 0

    if profile_user :
        if profile_user[0].weight and profile_user[0].height :
            bmi = round(profile_user[0].weight/(profile_user[0].height**2)*10000,1)

    return render(request, 'tracker/tracker_profile.html', {
            'form': form ,
            'entries_count': Entries.objects.all()
                                      .filter(Username=username,Tracking="Exercise")
                                      .exclude(Additional_Information="Skipped")
                                      .order_by('-DateTime').count(),

            'exercises_skipped': Entries.objects.all()
                                      .filter(Username=username,Tracking="Exercise",Additional_Information="Skipped")
                                      .count(),

            'exercises_by_day' : Entries.objects.annotate(day=TruncDay('DateTime'))
                                                .filter(Username=username,Tracking="Exercise")
                                                .exclude(Additional_Information="Skipped")
                                                .values('day')
                                                .annotate(total=Count('id')),
            'form' : form,
            'profile_user' : profile_user,
            'bmi' : bmi,
            'social_user' : social_user

        } )

tracker/templates/tracker/tracker_dashboard.html
{% extends 'base.html' %}
{% block dashboard_active %}class="active"{% endblock %}
{% block title %}Dashboard{% endblock %}
{% block content %}
<script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>

<div class="content">
<center>


	<div id="container" style="width: 75%;">
    <canvas id="exercise_canvas" width="400" height="100"></canvas>
	</div>

	<script>

new Chart(document.getElementById("exercise_canvas"), {
    type: 'bar',
    data: {
      labels: {{ exercise_labels | safe }},
      datasets: [
        {
          label: "Exercise (Minutes Per Day)",
          backgroundColor: "#4CAF50",
          data: {{ exercise_data | safe }}
        }
      ]
    },
    options: {
      legend: { display: false },
      title: {
        display: true,
        text: "Exercise (Minutes Per Day)"
      }
    }
});

	</script>


</center>
</div>

{% endblock %}

tracker/templates/tracker/tracker_exercise.html
{% extends 'base.html' %}
{% block title %}{{ exercise }}{% endblock %}
{% block exercise_active %}class="active"{% endblock %}
{% block head_javascript %}
  <script type="text/javascript">
    //<![CDATA[

    window.onload = function() {

      var seconds = document.getElementById("countdown").textContent;
      var countdown = setInterval(function() {
        seconds--;
        document.getElementById("countdown").textContent = seconds;
        if (seconds <= 10) {
          document.getElementById("exercise_state").textContent = "Rest";
          document.getElementById("exercise_state").style.color = 'orange';

        }
        if (seconds <= 0) {
          document.getElementById("exercise_state").textContent = "Exercise";
          document.getElementById("exercise_state").style.color = 'green';
          data = new FormData()
          data.set('complete_exercise_id',{{ exercise_id }})
          let request = new XMLHttpRequest();
          request.open("POST", "{% url 'tracker:tracker_exercise' %}", true);
          request.setRequestHeader("X-CSRFTOKEN", "{{ csrf_token }}");
          request.send(data)
          location.reload();
        }
      }, 1000);

    }

    //]]>
  </script>
{% endblock %}
{% block content %}

<div class="content">
  <center>
    <div id="block_container">
      <div id="bloc1">
        <font color="green"><span id="exercise_state">Exercise</span> :</font><span id="countdown">{{ countdown_number }}</span> seconds
      </div>
      <div id="bloc2">
        <form action="/tracker/exercise/" method="post">
          <input type="hidden" id="skip_exercise_id" name="skip_exercise_id" value="{{ exercise_id }}">
          <button type="submit">Skip Exercise</button>
          {% csrf_token %}
        </form>
      </div>

      <div id="bloc3">
        <font color="blue">Exercise Count :</font> {{ entries_count }}
      </div>
    </div>
  </center>

  <div class="videoWrapper">
    <iframe width="80%" height="60%" src="https://www.youtube.com/embed/{{ exercise.id }}?loop=1&autoplay=1&mute=1&playlist={{ exercise.id }}&controls=0&modestbranding=1" frameborder="0"
      allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture,playsinline,webkit-playsinline">
    </iframe>
  </div>
<center>
{% load render_table from django_tables2 %}
{% render_table entriestable %}
</center>
</div>


{% endblock %}

tracker/templates/tracker/tracker_list.html
{% extends 'base.html' %}
{% block title %}Home{% endblock %}
{% block home_active %}class="active"{% endblock %}
{% load static %}
{% block meta_tags %}
  <meta property="og:title" content="Random Workout Generator">
  <meta property="og:image" content="{% static 'images/workout.png' %}">
  <meta property="og:description" content="Workout from over 200+ bodyweight exercises in the DareBee workout library, no equipment required!">
{% endblock %}
{% block content %}



<center>

  <p>
    <h1>Random Workout Generator,    <div class="fb-like" data-href="https://exercise.laverty.ws/" data-width="" data-layout="button_count" data-action="like" data-size="large" data-share="true">
                          </div></h1>

  </p>

  <p>This website is a <a href="https://en.wikipedia.org/wiki/High-intensity_interval_training" target="_blank">High-intensity interval training</a> application
    that will give you a randomly selected exercise from the <a href="https://www.youtube.com/playlist?list=PLQSMS0J6JbrKdSOSbyJXaQ_zN_HSSp7zZ" target="_blank">DareBee workout library</a>.</p>
  <p>These exercises do not require any equipment.</p>
  <p>You will have <b>60</b> seconds to perform the exercise and then the page will reload with another random exercise.</p>
  <p>If you don't like an exercise click <b>Skip Exercise</b> and you will move on to the next exercise.</p>
  <p>There are currently <b>{{ exercise_count }}</b> exercises available.</p>
  <p>There have been a total of <b>{{ entries_count }}</b> exercises performed on this website.</p>
  <p>To get started you can either sign in as a <a href="{% url 'tracker:tracker_exercise' %}" target="_blank">guest</a> or <a href="{% url 'users:signup' %}">sign up</a> for an account if you want to record your workout history.</p>
  <p>Note videos will not autoplay on iPhone and iPads due to Apple disabling autoplay to "save user data"...</p>
  <p>The source code for the site is hosted in Github here <a href="https://github.com/alexlaverty/exercise" target="_blank">Github.com/alexlaverty/exercise</a></p>
  <p>Feel free to raise an <a href="https://github.com/alexlaverty/exercise/issues" target="_blank">Issue</a> or <a href="https://github.com/alexlaverty/exercise/pulls" target="_blank">PR</a></p>
  <a href="{% url 'tracker:tracker_exercise' %}" target="_blank">
    <img src="{% static 'images/workout.png' %}" height="350px" width="600px">
  </a>



<h1>Today's Top Users</h1>

<table>
  <tr><td></td><td><b>User</b></td><td><b>Exercises Performed</b></td></tr>
{% for today_user in todays_top_users %}
  <tr><td>{% if today_user.fbid %}
  <img class="roundrect" src="https://graph.facebook.com/{{ today_user.fbid }}/picture?type=large&width=75&height=75">
  {% endif %}</td><td>{{ today_user.Username }}</td><td>{{ today_user.total }}</td></tr>
{% endfor %}
</table>
<h1>All Time Top Users</h1>

{% for user in top_users %}

{{ user.Username }} has performed a total of {{ user.total }} exercises<br>

{% endfor %}

<table>
  <tr><td></td><td><b>User</b></td><td><b>Exercises Performed</b></td></tr>
{% for user in top_users %}
  <tr><td>{% if user.fbid %}
  <img class="roundrect" src="https://graph.facebook.com/{{ user.fbid }}/picture?type=large&width=75&height=75">
  {% endif %}</td><td>{{ user.Username }}</td><td>{{ user.total }}</td></tr>
{% endfor %}
</table>

<h1>Top 10 Performed Exercises</h1>

<table>
  <tr><td><b>Exercise</b></td><td><b>Total Performed</b></td></tr>
{% for exercise in top_exercises %}
  <tr><td>{{ exercise.String_Value }}</td><td>{{ exercise.total }}</td></tr>
{% endfor %}
</table>

<h1>Top 10 Most Skipped Exercises</h1>

<table>
  <tr><td><b>Exercise</b></td><td><b>Total Skipped</b></td></tr>
{% for skipped_exercise in top_exercise_skipped %}
  <tr><td>{{ skipped_exercise.String_Value }}</td><td>{{ skipped_exercise.total }}</td></tr>
{% endfor %}
</table>

<hr>

<h1>Leave A Comment</h1>
Leave a comment, feedback or feature request :
<div id="fb-root"></div>
<script async defer crossorigin="anonymous"
src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v6.0&appId=240725712750785&autoLogAppEvents=1">
</script>
<div class="fb-comments" data-href="https://exercise.laverty.ws/" data-width="" data-numposts="5"></div>

<!-- <h1>Today's User Activity</h1>

{% load render_table from django_tables2 %}
{% render_table entriestable %} -->

</center>

{% endblock %}

tracker/templates/tracker/tracker_profile.html
{% extends 'base.html' %}
{% block title %}{{ user }}{% endblock %}
{% block profile_active %}class="active"{% endblock %}
{% block content %}

<div class="content">

  <div id="profilecontent">
        <h2>Update Profile Settings :</h2>

        <form method="POST" class="post-form">{% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="save btn btn-default">Save</button>
        </form>
    <table class="profiletable" border="1" cellpadding="10">
      <tbody>
        <tr>
          <td valign="top">
            <h2>{{ user }}</h2>
          </td>
          <td>{% if social_user %}<img class="roundrect" src="https://graph.facebook.com/{{ social_user.uid }}/picture?type=large&width=200&height=200">{% endif %}</td>
        </tr>
        <tr>
          <td>Age</td>
          <td>{{ profile_user.0.age }}</td>
        </tr>
        <tr>
          <td>Height</td>
          <td>{{ profile_user.0.height }}</td>
        </tr>
        <tr>
          <td>Weight</td>
          <td>{{ profile_user.0.weight }}</td>
        </tr>
        <tr>
          <td>Total Exercises Performed </td>
          <td>{{ entries_count }}</td>
        </tr>
        <tr>
          <td>Total Minutes Worked out </td>
          <td>{{ entries_count }}</td>
        </tr>
        <tr>
          <td>Total Exercises Skipped </td>
          <td>{{ exercises_skipped }}</td>
        </tr>
        <tr>
          <td valign="top">Exercise Count by Day :</td>
          <td>

            {% for day in exercises_by_day %}

            {{ day.day | date:'d/m/Y' }} : {{day.total}}<br>

            {% endfor %}

          </td>
        </tr>
        <tr>
          <td>Exercise Countdown Number </td>
          <td>{{ profile_user.0.countdown_number }}</td>
        </tr>
      </tbody>
    </table>
    <br>



  </div>
</div>

{% endblock %}